apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  namespace: mlflow  # Ensure the namespace matches
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow-container
          image: localhost:5000/mlflow:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000
          env:
            - name: MLFLOW_PORT
              value: "5000"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DB_NAME
            - name: ARTIFACT_ROOT
              value: "/data/mlflow"  # Sync this path
          volumeMounts:
            - name: mlflow-data
              mountPath: /data/mlflow  # Ensure this matches the hostPath defined in PV
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /  # Any path you know is always available
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3

      volumes:
        - name: mlflow-data
          persistentVolumeClaim:
            claimName: mlflow-data-pvc  # Ensure this matches the PVC name
