apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: mlflow  # Replace with your namespace
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=  # Encoded Username
  DB_PASSWORD: MnBoUG1NU0FmSg==  # Encoded Password
