
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-data-pv
  namespace: mlflow  # Replace with your namespace if necessary
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # Ensure this matches the PVC's storage class (if defined)
  hostPath:
    path: /data/mlflow  # Adjust this path based on your infrastructure

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data-pvc
  namespace: mlflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual  # Match with the PV's storageClassName
