apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-0
  namespace: aderadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Redis usually requires much less space
  storageClassName: standard
