# Redis Deployment Configuration

# Redis Configuration
usePassword: true  # Set password for Redis to secure access
password:
  secretKeyRef:
    name: redis-password
    key: password  # stored in Kubernetes secrets

# Kubernetes resources
resources:
  requests:
    memory: "128Mi"
    cpu: "80m"
  limits:
    memory: "256Mi"
    cpu: "200m"

# Persistence settings
persistence:
  enabled: true
  storageClass: "standard"
  existingClaim: data-redis-0  # Reuse the existing PVC 'data-redis-0'
  mountPath: "/bitnami/redis/data"  # Use the default mount path for Redis
  # Ensure no conflicting overrides occur
  master:
    persistence:
      existingClaim: data-redis-0  # Reference the same PVC for master
  replica:
    persistence:
      existingClaim: data-redis-0 
# High Availability setup: Redis Master-Slave with replication
replica:
  enabled: true
  replicaCount: 1  # 1 master + 2 replicas
